name: survival-analysis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - lifelines
  - statsmodels
  - pyyaml        
  - ipykernel
  - notebook      
